---
title: ""
---

# Goals of the project

The Play & Learning Across a Year (PLAY) project serves as a model system for doing development science from a “big data” approach. 
Natural free play represents the foundation of infant learning, but we know little about how infants play, how play unfolds in real time and across development, and how individual and group differences promote infant learning and development through play. 
To answer these questions, the PLAY project will collect, code, and share 900 hours of video collected in the homes of children at 12, 18, and 24 months of age drawn from 30 sites across North America.

The aim of the project is to develop a new approach to developmental science that enables: (1) “big data“ science for researchers who would not otherwise have access; (2) a communal, low-cost means of collecting and coding data that retains the autonomy of individual labs; and (3) a plan for leveraging diverse expertise to address a common goal.

Materials (videos, questionnaires, links to Databrary) for the PLAY project are included in this site.
We document data collection protocols, workflows, coding strategies, and operational definitions.